pluginManagement {
    repositories {
        gradlePluginPortal()
        mavenCentral()
        google()
    }
}

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        mavenCentral()
        google()
        maven { url = "https://jitpack.io" }
    }
}

include ':app'
include ':catvod'
include ':chaquo'
include ':quickjs'
rootProject.name = "SpiderCheck"
